SET SERVEROUTPUT ON;

DECLARE 

	A CUSTOMER.CNAME%TYPE:='&a';
	C CUSTOMER.WNUM%TYPE:=&c;
	D CUSTOMER.TNUM%TYPE:=&d;
	E CUSTOMER.NCAGE%TYPE:=&e;
	F CUSTOMER.KCAGE%TYPE:=&f;
	
	G CALC.WP%TYPE;
	H CALC.TP%TYPE;
	I CALC.NP%TYPE;
	J CALC.KP%TYPE;
	
	K NUMBER := 0;
		
BEGIN

	INSERT INTO CUSTOMER VALUES (A,C,D,E,F);	
	
	SELECT WPRICE INTO G FROM COW@site_link WHERE WNUM=C;
	SELECT TPRICE INTO H FROM GOAT@site_link WHERE TNUM=D;
	SELECT NPRICE INTO I FROM CHICKEN@site_link WHERE NCAGE=E;
	SELECT KPRICE INTO J FROM DUCK@site_link WHERE KCAGE=F;

	K:=G+H+I+J;
	
	INSERT INTO CALC@site_link VALUES (A,G,H,I,J,K);
	
	DBMS_OUTPUT.PUT_LINE('TOTAL COST'||' '||K);
	
	DELETE FROM COW@site_link WHERE WNUM = C;
	DELETE FROM GOAT@site_link WHERE TNUM = D;
	DELETE FROM CHICKEN@site_link WHERE NCAGE = E;
	DELETE FROM DUCK@site_link WHERE KCAGE = F;
	
END;
/

SELECT * FROM CUSTOMER@site_link;

SELECT * FROM COW@site_link;

SELECT * FROM GOAT@site_link;

SELECT * FROM CHICKEN@site_link;

SELECT * FROM DUCK@site_link;

SELECT * FROM CALC@site_link;

COMMIT;