SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE MIN_MAX(M IN CALC.TOTAL%TYPE, N IN CALC.TOTAL%TYPE)
	IS
	
BEGIN
	DBMS_OUTPUT.PUT_LINE('Minimum SELL'||' '|| M);
	DBMS_OUTPUT.PUT_LINE('Maximum SELL'||' '|| N);
	
END MIN_MAX;
/