SET SERVEROUTPUT ON;

DECLARE
	A COW.WNUM%TYPE:=&a;
	B COW.WPRICE%TYPE:=&b;
	C COW.WWEIGHT%TYPE:=&c;
	D COW.EID%TYPE:=&d;

BEGIN
	INSERT INTO COW@site_link VALUES (A,B,C,D);
END;
/

SELECT * FROM COW@site_link;
SELECT * FROM LOG_INSERT@site_link;