SET SERVEROUTPUT ON;

DECLARE
	A CHICKEN.NCAGE%TYPE:=&a;
	B CHICKEN.NPRICE%TYPE:=&b;

BEGIN
	UPDATE CHICKEN@site_link SET NPRICE=B WHERE NCAGE=A;
END;
/

SELECT * FROM CHICKEN@site_link;
SELECT * FROM LOG_UPDEL@site_link;
COMMIT;
