SET SERVEROUTPUT ON;

DECLARE
	A COW.WNUM%TYPE:=&a;
	B COW.WPRICE%TYPE:=&b;

BEGIN
	UPDATE COW@site_link SET WPRICE=B WHERE WNUM=A;
END;
/

SELECT * FROM COW@site_link;
SELECT * FROM LOG_UPDEL@site_link;
COMMIT;
