SET SERVEROUTPUT ON;

DECLARE
	A DUCK.KCAGE%TYPE:=&a;
	B DUCK.KPRICE%TYPE:=&b;

BEGIN
	UPDATE DUCK@site_link SET KPRICE=B WHERE KCAGE=A;
END;
/

SELECT * FROM DUCK@site_link;
SELECT * FROM LOG_UPDEL@site_link;
COMMIT;
