SET SERVEROUTPUT ON;

DECLARE
	A GOAT.TNUM%TYPE:=&a;
	B GOAT.TPRICE%TYPE:=&b;

BEGIN
	UPDATE GOAT@site_link SET TPRICE=B WHERE TNUM=A;
END;
/

SELECT * FROM GOAT@site_link;
SELECT * FROM LOG_UPDEL@site_link;
COMMIT;
