SET SERVEROUTPUT ON;

DECLARE
	A CHICKEN.NCAGE%TYPE:=&a;
	B CHICKEN.NQUANTIY%TYPE:=&b;
	C CHICKEN.NPRICE%TYPE:=&c;
	D CHICKEN.NWEIGHT%TYPE:=&d;
	E CHICKEN.EID%TYPE:=&e;

BEGIN
	INSERT INTO CHICKEN@site_link VALUES (A,B,C,D,E);
END;
/

SELECT * FROM CHICKEN@site_link;
SELECT * FROM LOG_INSERT@site_link;