SET SERVEROUTPUT ON;

DECLARE
	A DUCK.KCAGE%TYPE:=&a;
	B DUCK.KQUANTIY%TYPE:=&b;
	C DUCK.KPRICE%TYPE:=&c;
	D DUCK.KWEIGHT%TYPE:=&d;
	E DUCK.EID%TYPE:=&e;

BEGIN
	INSERT INTO DUCK@site_link VALUES (A,B,C,D,E);
END;
/

SELECT * FROM DUCK@site_link;
SELECT * FROM LOG_INSERT@site_link;