SET SERVEROUTPUT ON;

DECLARE
	A GOAT.TNUM%TYPE:=&a;
	B GOAT.TPRICE%TYPE:=&b;
	C GOAT.TWEIGHT%TYPE:=&c;
	D GOAT.EID%TYPE:=&d;

BEGIN
	INSERT INTO GOAT@site_link VALUES (A,B,C,D);
END;
/

SELECT * FROM GOAT@site_link;
SELECT * FROM LOG_INSERT@site_link;