SET SERVEROUTPUT ON;

DECLARE 
	C NUMBER;
	T NUMBER;
	N NUMBER;
	K NUMBER;
BEGIN 
   C:=TOTALGOAT();
   DBMS_OUTPUT.PUT_LINE('TOTAL NO. OF COWS: '||C);
   
   T:=TOTALGOAT();
   DBMS_OUTPUT.PUT_LINE('TOTAL NO. OF GOATS: '||T);
   
   N:=TOTALCHICKEN();
   DBMS_OUTPUT.PUT_LINE('TOTAL NO. OF CHICKENS: '||N);
   
   K:=TOTALDUCK();
   DBMS_OUTPUT.PUT_LINE('TOTAL NO. OF DUCKS: '||K);
END; 
/