CREATE OR REPLACE TRIGGER TRIGGER_LOGUP_COW
AFTER UPDATE ON COW FOR EACH ROW
BEGIN
	INSERT INTO LOG_UPDEL@site_link VALUES(:OLD.WPRICE,:NEW.WPRICE,SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRIGGER_LOGUP_GOAT
AFTER UPDATE ON GOAT FOR EACH ROW
BEGIN
	INSERT INTO LOG_UPDEL@site_link VALUES(:OLD.TPRICE,:NEW.TPRICE,SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRIGGER_LOGUP_CHICKEN
AFTER UPDATE ON CHICKEN FOR EACH ROW
BEGIN
	INSERT INTO LOG_UPDEL@site_link VALUES(:OLD.NPRICE,:NEW.NPRICE,SYSDATE);
END;
/

CREATE OR REPLACE TRIGGER TRIGGER_LOGUP_DUCK
AFTER UPDATE ON DUCK FOR EACH ROW
BEGIN
	INSERT INTO LOG_UPDEL@site_link VALUES(:OLD.KPRICE,:NEW.KPRICE,SYSDATE);
END;
/