CREATE OR REPLACE VIEW MYVIEW AS
	SELECT DISTINCT ENAME,EID FROM EMPLOYEE@site_link E INNER JOIN CHICKEN@site_link N ON E.EID=N.EID INNER JOIN DUCK@site_link K ON N.EID=K.EID;

SELECT * FROM MYVIEW;

COMMIT;